### ISSUE TITLE
> Task :gms:impl:integrationTest fails

### ISSUE THREAD

**Issue by luck02** [linkedin/datahub#2088]
OS: Fedora 33

I get this in the terminal and via intellij IDE.

I have docker / docker-compose installed and I seem to be able to run the quickstart script.  

I've pulled datahub locally and am running `gradlew build` 

All tests except these are passing:

```
> Task :gms:impl:integrationTest

com.linkedin.metadata.ChartSearchSanityTest > initializationError FAILED
    org.testcontainers.containers.ContainerLaunchException
        Caused by: org.rnorth.ducttape.RetryCountExceededException
        Caused by: org.rnorth.ducttape.RetryCountExceededException

            Caused by: org.testcontainers.containers.ContainerLaunchException
            Caused by: org.testcontainers.containers.ContainerLaunchException

                Caused by: java.lang.IllegalStateException
                Caused by: java.lang.IllegalStateException


> Task :gms:impl:integrationTest

com.linkedin.metadata.DataProcessSearchSanityTest > initializationError FAILED
    org.testcontainers.containers.ContainerLaunchException
        Caused by: org.rnorth.ducttape.RetryCountExceededException
            Caused by: org.testcontainers.containers.ContainerLaunchException
        Caused by: org.rnorth.ducttape.RetryCountExceededException

            Caused by: org.testcontainers.containers.ContainerLaunchException

                Caused by: java.lang.IllegalStateException
                Caused by: java.lang.IllegalStateException


> Task :gms:impl:integrationTest

com.linkedin.metadata.DatsetsSearchSanityTest > initializationError FAILED
    org.testcontainers.containers.ContainerLaunchException
        Caused by: org.rnorth.ducttape.RetryCountExceededException
        Caused by: org.rnorth.ducttape.RetryCountExceededException

            Caused by: org.testcontainers.containers.ContainerLaunchException
                Caused by: java.lang.IllegalStateException
            Caused by: org.testcontainers.containers.ContainerLaunchException

                Caused by: java.lang.IllegalStateException


> Task :gms:impl:integrationTest

com.linkedin.metadata.CorpUserSearchSanityTest > initializationError FAILED
    org.testcontainers.containers.ContainerLaunchException
        Caused by: org.rnorth.ducttape.RetryCountExceededException
            Caused by: org.testcontainers.containers.ContainerLaunchException
        Caused by: org.rnorth.ducttape.RetryCountExceededException

            Caused by: org.testcontainers.containers.ContainerLaunchException

                Caused by: java.lang.IllegalStateException
                Caused by: java.lang.IllegalStateException


> Task :gms:impl:integrationTest

com.linkedin.metadata.DashboardSearchSanityTest > initializationError FAILED
    org.testcontainers.containers.ContainerLaunchException
        Caused by: org.rnorth.ducttape.RetryCountExceededException
            Caused by: org.testcontainers.containers.ContainerLaunchException
        Caused by: org.rnorth.ducttape.RetryCountExceededException

                Caused by: java.lang.IllegalStateException
            Caused by: org.testcontainers.containers.ContainerLaunchException

                Caused by: java.lang.IllegalStateException


5 tests completed, 5 failed

> Task :gms:impl:integrationTest FAILED

Execution failed for task ':gms:impl:integrationTest'.
> There were failing tests. See the report at: file:///home/garylucas/dev/datahub/gms/impl/build/reports/tests/integrationTest/index.html
```
I've dug around trying to get some more details on what is actually failing during initialization but I'm not familiar with org.testcontainers or how their being used in this project.

I'm inclined to just ignore as it's not reallly stopping me from continuing to evaluate datahub, but I am curious about what is causing the failure.

Any troubleshooting steps would be appreciated.

**Comment by shirshanka** [comment]
@luck02 : Are you on the latest? We thought we fixed it with this upgrade. (https://github.com/linkedin/datahub/pull/2085)

**Comment by shirshanka** [comment]
The workaround if that doesn't work for you, seems to be "clear / purge data from docker" 

https://github.com/testcontainers/testcontainers-java/issues/3574#issuecomment-752917437

**Comment by luck02** [comment]
I pulled the repo yesterday around 7pm Pacific.  I've since pulled again, I did get an update but problem persisted.

I'm on fedora so there's no docker desktop for that environment but I did clean / prune everything, that should accomplish the same thing.  IE `docker prune -a` 

In any case I'm still seeing the error:

I'm on:
```
commit 6c04ba1ebcc3c7e9f3fef0c02c04b1266a0d7f23 (HEAD -> master, origin/master, origin/HEAD)
```
I see the commit from https://github.com/linkedin/datahub/pull/2085 a few commits back in the git log and I certainly seem to be on the tip of origin/master.

Thanks for looking in!

**Comment by jjoyce0510** [comment]
A fresh `docker build` also does not work? We're seeing similar issues on other Linux deployments. If this does not work either let me know. In the meantime we will be looking into this further

**Comment by hsheth2** [comment]
In the short-term, as per https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html, you can run this command on your machine to make the tests pass:
```sh
sudo sysctl -w vm.max_map_count=262144
```

Alternatively, you could skip the tests using `./gradlew build -x check`. 

Once https://github.com/linkedin/datahub-gma/pull/76 gets merged and then integrated into this datahub repo, the tests should start passing without any extra changes.

**Comment by luck02** [comment]
Thanks a bunch!  the feedback is appreciated!

**Comment by shirshanka** [comment]
@luck02 : could you verify if this now works for you?

**Comment by luck02** [comment]
> @luck02 : could you verify if this now works for you?

Will do this evening :D

**Comment by luck02** [comment]
I pulled latest this evening and confirmed I saw #2094 in the log, issue is resolved.

Thanks!
